export * from './course.service';
export * from './file.service';
export * from './hero.service';
export * from './information.service';
export * from './method-course.service';
export * from './plan.service';
export * from './review.service';
export * from './teacher.service';
export * from './form-study.service';